# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCalendarWidget, QFrame, QLabel,
    QMainWindow, QPushButton, QSizePolicy, QStackedWidget,
    QTextEdit, QWidget)
import rc_resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 530)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.MainWidget = QWidget(self.centralwidget)
        self.MainWidget.setObjectName(u"MainWidget")
        self.MainWidget.setGeometry(QRect(0, 0, 801, 541))
        self.MainPage = QWidget(self.MainWidget)
        self.MainPage.setObjectName(u"MainPage")
        self.MainPage.setGeometry(QRect(0, 0, 811, 541))
        self.Menu = QPushButton(self.MainPage)
        self.Menu.setObjectName(u"Menu")
        self.Menu.setGeometry(QRect(10, 30, 89, 25))
        icon = QIcon()
        icon.addFile(u":/icons/images/icons/list-view-16.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.Menu.setIcon(icon)
        self.Menu.setCheckable(True)
        self.Menu.setAutoExclusive(True)
        self.stackedWidget = QStackedWidget(self.MainPage)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(270, 30, 531, 521))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.frame = QFrame(self.page)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(0, 30, 231, 171))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label = QLabel(self.frame)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(10, 16, 51, 41))
        self.label.setTextFormat(Qt.PlainText)
        self.label.setPixmap(QPixmap(u":/crypto/images/crypto/icons8-crypto-48.png"))
        self.value1 = QLabel(self.frame)
        self.value1.setObjectName(u"value1")
        self.value1.setGeometry(QRect(70, 40, 81, 21))
        self.label_5 = QLabel(self.frame)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 60, 41, 61))
        self.label_5.setPixmap(QPixmap(u":/crypto/images/crypto/icons8-ethereum-48.png"))
        self.value2 = QLabel(self.frame)
        self.value2.setObjectName(u"value2")
        self.value2.setGeometry(QRect(70, 80, 71, 31))
        self.name = QLabel(self.frame)
        self.name.setObjectName(u"name")
        self.name.setGeometry(QRect(70, 20, 67, 17))
        self.name1 = QLabel(self.frame)
        self.name1.setObjectName(u"name1")
        self.name1.setGeometry(QRect(70, 70, 67, 17))
        self.frame_2 = QFrame(self.page)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(260, 30, 251, 171))
        self.frame_2.setFrameShape(QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.currency1 = QLabel(self.frame_2)
        self.currency1.setObjectName(u"currency1")
        self.currency1.setGeometry(QRect(20, 20, 71, 17))
        self.currency_price1 = QLabel(self.frame_2)
        self.currency_price1.setObjectName(u"currency_price1")
        self.currency_price1.setGeometry(QRect(20, 50, 67, 17))
        self.currency2 = QLabel(self.frame_2)
        self.currency2.setObjectName(u"currency2")
        self.currency2.setGeometry(QRect(20, 80, 81, 17))
        self.currency_price2 = QLabel(self.frame_2)
        self.currency_price2.setObjectName(u"currency_price2")
        self.currency_price2.setGeometry(QRect(20, 110, 67, 17))
        self.currency3 = QLabel(self.frame_2)
        self.currency3.setObjectName(u"currency3")
        self.currency3.setGeometry(QRect(140, 20, 71, 17))
        self.currency_price3 = QLabel(self.frame_2)
        self.currency_price3.setObjectName(u"currency_price3")
        self.currency_price3.setGeometry(QRect(140, 50, 81, 17))
        self.frame_3 = QFrame(self.page)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(0, 220, 511, 231))
        self.frame_3.setFrameShape(QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.finance1 = QLabel(self.frame_3)
        self.finance1.setObjectName(u"finance1")
        self.finance1.setGeometry(QRect(50, 30, 67, 17))
        self.finance2 = QLabel(self.frame_3)
        self.finance2.setObjectName(u"finance2")
        self.finance2.setGeometry(QRect(50, 90, 67, 17))
        self.finance3 = QLabel(self.frame_3)
        self.finance3.setObjectName(u"finance3")
        self.finance3.setGeometry(QRect(300, 30, 67, 17))
        self.finance4 = QLabel(self.frame_3)
        self.finance4.setObjectName(u"finance4")
        self.finance4.setGeometry(QRect(300, 90, 67, 17))
        self.finance_price1 = QLabel(self.frame_3)
        self.finance_price1.setObjectName(u"finance_price1")
        self.finance_price1.setGeometry(QRect(50, 60, 67, 17))
        self.finance_price2 = QLabel(self.frame_3)
        self.finance_price2.setObjectName(u"finance_price2")
        self.finance_price2.setGeometry(QRect(50, 120, 67, 17))
        self.finance_price3 = QLabel(self.frame_3)
        self.finance_price3.setObjectName(u"finance_price3")
        self.finance_price3.setGeometry(QRect(300, 60, 67, 17))
        self.finance_price4 = QLabel(self.frame_3)
        self.finance_price4.setObjectName(u"finance_price4")
        self.finance_price4.setGeometry(QRect(300, 120, 67, 17))
        self.stackedWidget.addWidget(self.page)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.save = QPushButton(self.page_3)
        self.save.setObjectName(u"save")
        self.save.setGeometry(QRect(380, 450, 89, 25))
        self.textEdit = QTextEdit(self.page_3)
        self.textEdit.setObjectName(u"textEdit")
        self.textEdit.setGeometry(QRect(30, 180, 461, 221))
        self.read = QPushButton(self.page_3)
        self.read.setObjectName(u"read")
        self.read.setGeometry(QRect(260, 450, 89, 25))
        self.calendar = QCalendarWidget(self.page_3)
        self.calendar.setObjectName(u"calendar")
        self.calendar.setGeometry(QRect(30, 0, 456, 171))
        self.stackedWidget.addWidget(self.page_3)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 180, 67, 17))
        self.stackedWidget.addWidget(self.page_2)
        self.MenuBig = QFrame(self.MainPage)
        self.MenuBig.setObjectName(u"MenuBig")
        self.MenuBig.setGeometry(QRect(90, 80, 191, 471))
        self.Homepage = QPushButton(self.MenuBig)
        self.Homepage.setObjectName(u"Homepage")
        self.Homepage.setGeometry(QRect(20, 90, 121, 25))
        icon1 = QIcon()
        icon1.addFile(u":/icons/images/icons/home-5-16.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.Homepage.setIcon(icon1)
        self.Homepage.setCheckable(True)
        self.Homepage.setAutoExclusive(True)
        self.Chats = QPushButton(self.MenuBig)
        self.Chats.setObjectName(u"Chats")
        self.Chats.setGeometry(QRect(20, 140, 89, 25))
        icon2 = QIcon()
        icon2.addFile(u":/icons/images/icons/edit-6-16.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.Chats.setIcon(icon2)
        self.Chats.setCheckable(True)
        self.Chats.setAutoExclusive(True)
        self.Tasks = QPushButton(self.MenuBig)
        self.Tasks.setObjectName(u"Tasks")
        self.Tasks.setGeometry(QRect(20, 190, 89, 25))
        icon3 = QIcon()
        icon3.addFile(u":/icons/images/icons/folder-2-16.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.Tasks.setIcon(icon3)
        self.Tasks.setCheckable(True)
        self.Tasks.setAutoExclusive(True)
        self.Settings = QPushButton(self.MenuBig)
        self.Settings.setObjectName(u"Settings")
        self.Settings.setGeometry(QRect(20, 224, 89, 31))
        self.pushButton_2 = QPushButton(self.MenuBig)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 400, 89, 25))
        self.MenuShort = QWidget(self.MainPage)
        self.MenuShort.setObjectName(u"MenuShort")
        self.MenuShort.setGeometry(QRect(0, 80, 81, 471))
        self.Home = QPushButton(self.MenuShort)
        self.Home.setObjectName(u"Home")
        self.Home.setGeometry(QRect(10, 90, 61, 25))
        self.Home.setStyleSheet(u"image: url(:/icons/images/icons/home-5-16.ico);")
        self.Home.setCheckable(True)
        self.Home.setAutoExclusive(True)
        self.Chat = QPushButton(self.MenuShort)
        self.Chat.setObjectName(u"Chat")
        self.Chat.setGeometry(QRect(10, 140, 61, 25))
        self.Chat.setStyleSheet(u"image: url(:/icons/images/icons/edit-6-16.ico);")
        self.Chat.setCheckable(True)
        self.Chat.setAutoExclusive(True)
        self.pushButton_5 = QPushButton(self.MenuShort)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(10, 190, 61, 25))
        self.pushButton_5.setStyleSheet(u"image: url(:/icons/images/icons/folder-2-16.ico);")
        self.pushButton_5.setCheckable(False)
        self.pushButton_5.setAutoExclusive(True)
        self.Setting = QPushButton(self.MenuShort)
        self.Setting.setObjectName(u"Setting")
        self.Setting.setGeometry(QRect(10, 224, 61, 31))
        self.pushButton = QPushButton(self.MenuShort)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(10, 400, 61, 25))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.Menu.toggled.connect(self.MenuBig.setVisible)
        self.Menu.toggled.connect(self.MenuShort.setHidden)
        self.Home.toggled.connect(self.Homepage.setChecked)
        self.Chat.toggled.connect(self.Chats.setChecked)
        self.pushButton_5.toggled.connect(self.Tasks.setChecked)
        self.Homepage.toggled.connect(self.Home.setChecked)
        self.Chats.toggled.connect(self.Chat.setChecked)
        self.Tasks.toggled.connect(self.pushButton_5.setChecked)
        self.Setting.toggled.connect(self.Settings.setChecked)
        self.Settings.toggled.connect(self.Setting.setChecked)
        self.pushButton.toggled.connect(self.pushButton_2.setChecked)
        self.pushButton_2.toggled.connect(self.pushButton.setChecked)
        self.pushButton_2.clicked.connect(MainWindow.close)
        self.pushButton.clicked.connect(MainWindow.close)

        self.stackedWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.Menu.setText(QCoreApplication.translate("MainWindow", u"Menu", None))
        self.label.setText("")
        self.value1.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.label_5.setText("")
        self.value2.setText(QCoreApplication.translate("MainWindow", u"value", None))
        self.name.setText(QCoreApplication.translate("MainWindow", u"name", None))
        self.name1.setText(QCoreApplication.translate("MainWindow", u"name", None))
        self.currency1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.currency_price1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.currency2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.currency_price2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.currency3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.currency_price3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance_price1.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance_price2.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance_price3.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.finance_price4.setText(QCoreApplication.translate("MainWindow", u"TextLabel", None))
        self.save.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.read.setText(QCoreApplication.translate("MainWindow", u"Read", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Chats", None))
        self.Homepage.setText(QCoreApplication.translate("MainWindow", u"Homepage", None))
        self.Chats.setText(QCoreApplication.translate("MainWindow", u"Chats", None))
        self.Tasks.setText(QCoreApplication.translate("MainWindow", u"Tasks", None))
        self.Settings.setText(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Exit", None))
        self.Home.setText("")
        self.Chat.setText("")
        self.pushButton_5.setText("")
        self.Setting.setText(QCoreApplication.translate("MainWindow", u"S", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"E", None))
    # retranslateUi

